server:
  port: 8080

spring:
  application:
    name: bff-gateway


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      routes:

        - id: middleware-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/products/**
            - Path=/api/v1/catalog/**
          filters:
            - AddRequestHeader=X-Gateway, bff
            - AddResponseHeader=X-BFF, gateway

        - id: system-admin
          uri: http://localhost:8081
          predicates:
            - Path=/admin/api/v1/**
          filters:
            - RewritePath=/admin(?<segment>/?.*), ${segment}

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
  sampling:
    probability: 1.0


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO