spring:
  application:
    name: middleware

server:
  port: 8082

system-api:
  url: http://localhost:8081

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: FULL